// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "System info and health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.HomeResponse"
                        }
                    }
                }
            }
        },
        "/api/danbooru/media": {
            "get": {
                "tags": [
                    "danbooru"
                ],
                "summary": "Proxy and stream Danbooru media",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Encoded Danbooru media URL",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Streams the media file"
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Failed to fetch media",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/danbooru/posts": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Fetches a list of posts from Danbooru based on provided tags.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "danbooru"
                ],
                "summary": "Fetch posts from Danbooru",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tags to search for",
                        "name": "tags",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max results (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Shuffle the results",
                        "name": "shuffle",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.DanbooruResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/danbooru/query_completion": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Provides tag completion via scraping Danbooru's tags directory (Eiyuu logic). Cached for 24 hours.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "danbooru"
                ],
                "summary": "Danbooru Tag Autocomplete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tag prefix to search for",
                        "name": "tags",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.QueryCompletionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/gelbooru/media": {
            "get": {
                "tags": [
                    "gelbooru"
                ],
                "summary": "Proxy and stream Gelbooru media",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Encoded Gelbooru media URL",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Streams the media file"
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Failed to fetch media",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/gelbooru/posts": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gelbooru"
                ],
                "summary": "Get posts from Gelbooru",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Space-separated tags",
                        "name": "tags",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max results (default 100, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.GelbooruResponse"
                        }
                    },
                    "502": {
                        "description": "Upstream fetch failed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/gelbooru/query_completion": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Scrapes autocomplete tags from Gelbooru using wildcard matching. No cache enforcement.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gelbooru"
                ],
                "summary": "Get tag completion from Gelbooru (Eiyuu logic)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tag query to autocomplete (e.g. jeanne)",
                        "name": "tags",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.QueryCompletionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/graphql": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "graphql"
                ],
                "summary": "GraphQL Endpoint",
                "parameters": [
                    {
                        "description": "GraphQL Query",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.GraphQLRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/hypnohub/media": {
            "get": {
                "produces": [
                    "*/*"
                ],
                "tags": [
                    "hypnohub"
                ],
                "summary": "Proxy Hypnohub Media",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Direct media URL to proxy",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Image or Video file"
                    },
                    "400": {
                        "description": "Missing or invalid URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to proxy media",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/hypnohub/posts": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hypnohub"
                ],
                "summary": "Fetch Hypnohub Posts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tags to search for",
                        "name": "tags",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Randomize the order of the results",
                        "name": "shuffle",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/hypnohub/query_completion": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hypnohub"
                ],
                "summary": "Hypnohub Tag Autocomplete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tag prefix to search",
                        "name": "tags",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/rule34/media": {
            "get": {
                "tags": [
                    "rule34"
                ],
                "summary": "Proxy and stream Rule34 media",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Encoded Rule34 media URL",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Streams the media file"
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Failed to fetch media",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/rule34/posts": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rule34"
                ],
                "summary": "Get posts from Rule34",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Space-separated tags",
                        "name": "tags",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max results (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Shuffle the results",
                        "name": "shuffle",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.Rule34Response"
                        }
                    },
                    "502": {
                        "description": "Upstream fetch failed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/rule34/query_completion": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Scrapes autocomplete tags from Rule34 using wildcard matching.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rule34"
                ],
                "summary": "Get tag completion from Rule34 (Eiyuu logic)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tag query to autocomplete (e.g. jeanne)",
                        "name": "tags",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.QueryCompletionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/safebooru/media": {
            "get": {
                "produces": [
                    "*/*"
                ],
                "tags": [
                    "safebooru"
                ],
                "summary": "Proxy Safebooru Media",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Direct media URL to proxy",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Image or Video file"
                    },
                    "400": {
                        "description": "Missing or invalid URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to proxy media",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/safebooru/posts": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "safebooru"
                ],
                "summary": "Fetch Safebooru Posts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tags to search for",
                        "name": "tags",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Randomize the order of the results",
                        "name": "shuffle",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/safebooru/query_completion": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "safebooru"
                ],
                "summary": "Safebooru Tag Autocomplete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tag prefix to search",
                        "name": "tags",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/tbib/media": {
            "get": {
                "tags": [
                    "tbib"
                ],
                "summary": "Proxy and stream TBIB media",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Encoded TBIB media URL",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Streams the media file"
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Failed to fetch media",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tbib/posts": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tbib"
                ],
                "summary": "Get posts from TBIB",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Space-separated tags",
                        "name": "tags",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max results (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Shuffle the results",
                        "name": "shuffle",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.TbibResponse"
                        }
                    },
                    "502": {
                        "description": "Upstream fetch failed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tbib/query_completion": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Scrapes autocomplete tags from TBIB using wildcard matching.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tbib"
                ],
                "summary": "Get tag completion from TBIB (Eiyuu logic)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tag query to autocomplete (e.g. yuri)",
                        "name": "tags",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.QueryCompletionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/xbooru/media": {
            "get": {
                "produces": [
                    "*/*"
                ],
                "tags": [
                    "xbooru"
                ],
                "summary": "Proxy Xbooru Media",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Direct media URL to proxy",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Image or Video file"
                    },
                    "400": {
                        "description": "Missing or invalid URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to proxy media",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/xbooru/posts": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "xbooru"
                ],
                "summary": "Fetch Xbooru Posts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tags to search for",
                        "name": "tags",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Randomize the order of the results",
                        "name": "shuffle",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/xbooru/query_completion": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "xbooru"
                ],
                "summary": "Xbooru Tag Autocomplete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tag prefix to search",
                        "name": "tags",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/graphql": {
            "get": {
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "graphql"
                ],
                "summary": "GraphiQL Playground",
                "responses": {
                    "200": {
                        "description": "GraphiQL HTML page",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Ping the server",
                "responses": {
                    "200": {
                        "description": "Server is running",
                        "schema": {
                            "$ref": "#/definitions/handlers.PingResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.DanbooruResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Post"
                    }
                },
                "provider": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "handlers.GelbooruResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Post"
                    }
                },
                "provider": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "handlers.GraphQLRequest": {
            "type": "object",
            "properties": {
                "operationName": {
                    "type": "string"
                },
                "query": {
                    "type": "string"
                },
                "variables": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "handlers.HomeResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "endpoint": {
                    "type": "string"
                },
                "heap": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "rss": {
                    "type": "string"
                },
                "server": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "uptime": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "handlers.PingResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "handlers.QueryCompletionResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handlers.Rule34Response": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Post"
                    }
                },
                "provider": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "handlers.TbibResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Post"
                    }
                },
                "provider": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "main.ErrorResponse": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.Post": {
            "type": "object",
            "properties": {
                "directory": {
                    "type": "string"
                },
                "file_url": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "matoi_file_url": {
                    "type": "string"
                },
                "matoi_preview_url": {
                    "type": "string"
                },
                "matoi_sample_url": {
                    "type": "string"
                },
                "preview_url": {
                    "type": "string"
                },
                "rating": {
                    "description": "s (safe), q (questionable), e (explicit)",
                    "type": "string"
                },
                "sample_url": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "source": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Provide the API key via the ` + "`" + `api_key` + "`" + ` query parameter or ` + "`" + `Authorization: Bearer \u003ckey\u003e` + "`" + ` header.",
            "type": "apiKey",
            "name": "api_key",
            "in": "query"
        }
    },
    "tags": [
        {
            "name": "graphql"
        },
        {
            "name": "danbooru"
        },
        {
            "name": "gelbooru"
        },
        {
            "name": "rule34"
        },
        {
            "name": "tbib"
        },
        {
            "name": "xbooru"
        },
        {
            "name": "hypnohub"
        },
        {
            "name": "safebooru"
        },
        {
            "name": "system"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "sinkaroid/matoi",
	Description:      "REST API wrapper/binding for imageboard APIs (Danbooru, Gelbooru, Rule34).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
