FROM ghcr.io/flaresolverr/flaresolverr:latest

# Environment variables to optimize for Matoi
ENV LOG_LEVEL=info
ENV LOG_HTML=false
ENV HEADLESS=true
ENV TEST_URL=https://konachan.com

# Expose standard FlareSolverr port
EXPOSE 8191
